- name: Install bind DNS server
  hosts: all
  become: yes
  tasks:

  - name: Install bind9
    apt:
      name: bind9
      state: present

  - name: Create bind directory
    file:
      path: /etc/bind
      state: directory
      owner: root
      group: root
      mode: 0755

  - name: Copy named.conf file
    copy:
      src: named.conf
      dest: /etc/bind/named.conf
      owner: root
      group: root
      mode: 0644
  
  - name: Allow Bind9 through firewall
    ufw:
      rule: allow
      name: Bind9

  - name: Enable Bind9
    systemd:
      name: bind9
      enabled: yes
  
  - name: Restart Bind9
    systemd:
      name: bind9
      state: restarted

# ansible-playbook -u omadmin -i '100.101.135.179,' bind9.yml