- name: Install Tailscale
  hosts: all
  become: yes
  tasks:

  # Add Tailscale’s package
  # https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
  - name: Add Tailscale’s package signing key
    apt_key:
      url: https://pkgs.tailscale.com/stable/ubuntu/jammy.noarmor.gpg
      state: present

  # add signing key and repository
  # https://pkgs.tailscale.com/stable/ubuntu/jammy.tailscale-keyring.list
  - name: Add Tailscale’s package repository
    apt_repository:
      repo: deb https://pkgs.tailscale.com/stable/ubuntu jammy main
      state: present

  # - name: Install Tailscale
  #   apt:
  #     name: tailscale
  #     state: present

# enable IP forwarding 
  - name: Enable IP forwarding
    sysctl:
      name: net.ipv4.ip_forward
      value: 1
      sysctl_set: yes
      state: present
      reload: yes
      
  - name: Run Tailscale up
    command: tailscale up --advertise-exit-node --advertise-routes=10.0.0.0/16 --authkey={{ tailscale_authkey }}
    register: tailscale_up
    changed_when: tailscale_up.stdout.find('Logged in') != -1x

### DNS Resolver ###

  # install bind DNS server
